apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: run-os
spec:
  label: dataplane-deployment-run-os
  role:
    name: "Deploy EDPM Operating System Run"
    hosts: "all"
    strategy: "linear"
    become: true
    tasks:
      - name: "Run edpm_sshd"
        import_role:
          name: "osp.edpm.edpm_sshd"
          tasks_from: "run.yml"
        tags:
          - "edpm_sshd"
      - name: "Run edpm_chrony"
        import_role:
          name: "osp.edpm.edpm_chrony"
          tasks_from: "run.yml"
        tags:
          - "edpm_chrony"
      - name: "Run edpm_chrony (Online)"
        import_role:
          name: "osp.edpm.edpm_chrony"
          tasks_from: "online.yml"
        tags:
          - "edpm_chrony"
      - name: "Run edpm_chrony (Sync)"
        import_role:
          name: "osp.edpm.edpm_chrony"
          tasks_from: "sync.yml"
        tags:
          - "edpm_chrony"
      - name: "Run edpm_timezone"
        import_role:
          name: "osp.edpm.edpm_timezone"
          tasks_from: "run.yml"
        tags:
          - "edpm_timezone"
      - name: "Run edpm_ovn"
        import_role:
          name: "osp.edpm.edpm_ovn"
          tasks_from: "run.yml"
        tags:
          - "edpm_ovn"
