apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: libvirt
spec:
  label: dataplane-deployment-libvirt
  role:
    name: "Deploy EDPM libvirt"
    hosts: "all"
    strategy: "linear"
    tasks:
      - name: "libvirt"
        import_role:
          name: "osp.edpm.edpm_libvirt"
        tags:
          - "edpm_libvirt"
