apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: install-ovn-bgp-agent
spec:
  label: dataplane-deployment-install-ovn-bgp-agent
  role:
    name: "Deploy EDPM OVN BGP Agent Install"
    hosts: "all"
    strategy: "linear"
    become: true
    tasks:
      - name: "Install edpm_ovn_bgp_agent"
        import_role:
          name: "osp.edpm.edpm_ovn_bgp_agent"
          tasks_from: "install.yml"
        tags:
          - "edpm_ovn_bgp_agent"
