apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: configure-ovn-bgp-agent
spec:
  label: dataplane-deployment-configure-ovn-bgp-agent
  playbook: osp.edpm.configure_ovn_bgp_agent
