apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: ovn
spec:
  playbook: osp.edpm.ovn
  configMaps:
  - ovncontroller-config
  tlsCert:
    contents:
    - dnsnames
    - ips
    networks:
    - ctlplane
    issuer: osp-rootca-issuer-ovn
    keyUsages:
      - digital signature
      - key encipherment
      - server auth
      - client auth
  caCerts: combined-ca-bundle
