apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: run-ovn-bgp-agent
spec:
  label: dataplane-deployment-run-ovn-bgp-agent
  role:
    name: "Deploy EDPM OVN BGP Agent Run"
    hosts: "all"
    strategy: "linear"
    become: true
    tasks:
      - name: "Run edpm_ovn_bgp_agent"
        import_role:
          name: "osp.edpm.edpm_ovn_bgp_agent"
          tasks_from: "run.yml"
        tags:
          - "edpm_ovn_bgp_agent"
