apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-sriov
spec:
  playbook: osp.edpm.neutron_sriov
  secrets:
  - neutron-sriov-agent-neutron-config
  addCertMounts: true
  caCerts: combined-ca-bundle
