apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: nova
spec:
  label: dataplane-deployment-nova
  secrets:
    - nova-cell1-compute-config
  playbook: osp.edpm.nova
