apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: libvirt
spec:
  playbook: osp.edpm.libvirt
  tlsCert:
    contents:
      - dnsnames
      - ips
    networks:
      - ctlplane
    keyUsages:
      - digital signature
      - key encipherment
      - server auth
      - client auth
    issuer: osp-rootca-issuer-internal
  caCerts: combined-ca-bundle
