apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: nova
spec:
  secrets:
    - nova-cell1-compute-config
    # NOTE: this Secret needs to be created before deploying the data plane.
    # It should contain an ssh key-pair in the secret fields: ssh-privatekey
    # and ssh-publickey
    - nova-migration-ssh-key
  playbook: osp.edpm.nova
  caCerts: combined-ca-bundle
  containerImageFields:
  - NovaComputeImage
  - EdpmIscsidImage
