# permissions for end users to view openstackdataplanenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackdataplanenode-viewer-role
rules:
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanenodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanenodes/status
  verbs:
  - get
