# permissions for end users to edit openstackdataplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackdataplane-editor-role
rules:
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanes/status
  verbs:
  - get
