# permissions for end users to edit openstackdataplaneroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackdataplanerole-editor-role
rules:
- apiGroups:
  - core.openstack.org
  resources:
  - openstackdataplaneroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openstack.org
  resources:
  - openstackdataplaneroles/status
  verbs:
  - get
