# permissions for end users to view openstackdataplaneroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackdataplanenodeset-viewer-role
rules:
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanenodesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanenodesets/status
  verbs:
  - get
