# permissions for end users to view openstackdataplaneroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackdataplanerole-viewer-role
rules:
- apiGroups:
  - core.openstack.org
  resources:
  - openstackdataplaneroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.openstack.org
  resources:
  - openstackdataplaneroles/status
  verbs:
  - get
