# permissions for end users to edit openstackdataplanenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackdataplanenode-editor-role
rules:
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanenodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataplane.openstack.org
  resources:
  - openstackdataplanenodes/status
  verbs:
  - get
