apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneRole
metadata:
  name: openstackdataplanerole-sample
spec:
  nodeTemplate:
    networkConfig:
      template: templates/net_config_bridge.j2
    managed: false
    managementNetwork: ctlplane
    ansibleUser: root
    ansiblePort: 22
